### ISSUE TITLE
Smart badge endorsement should be available to more users than professors

### ISSUE THREAD

**Issue by vkarakolis-epu** [QualiChain/verification#8]
Smart badge endorsements now is performed only from professors to learners. However, it is a pilot requirement to have students award Ph.D. students as exceptional instructors, as well as badge awarding within a company as part of the gamification.

**Comment by athird** [comment]
Fixed and deployed yesterday. :-)

There's a much deeper issue around this, though - currently, badge issuing involves a blockchain transaction signed by a single key which indicates "authorised to be issued by Qualichain". When we restrict this to educators, we can assume institutions authorise a particular badge. With this change, though, a student would be able to award themselves any badge at all - a full degree, for example - and when verified, it would look just the same as an honestly awarded badge for the same thing.

For now, we've added a check to make sure that the email address in the 'issuer' object matches the email address in the authorisation token, so we can identify issued badges by QC user accounts, but that's not great, either for fully solving the problem or for certain normal use cases (e.g., issuer email address is an institutional one, not the address of the QC educator who presses the issue button).

The _right_ solution would be to have client-side signing, either of the badge or of the blockchain transaction, but a good UX for that would be difficult - we'd need an easy and secure UI for private key management (any good off-the-shelf ones?) If we could solve this, there wouldn't be any need for a web service for badges at all, it could all be done in a browser Javascript library with very minimal changes to frontend code apart from key management.

Quicker not-so-good solutions would be:

1. Having multiple private keys in the issuing service, and using a different one depending on the QC role of the issuing user.
2. Adding an API to endorse an issued badge, with an OpenBadges Endorsement object, and second blockchain transaction, restricted to educators. This would need UI changes and an 'endorsing' workflow
3. Same as 2, but not performing any blockchain transaction for non-educator-issued badges until the endorsement workflow is complete. 
4. Storing 'permitted' student-issuable badges in the knowledge graph, and returning an error if a student account tries to issue a badge that isn't permitted.
5. Reverting to allowing only educators to issue badges, and having a separate service that automatically issues certain badges when specific triggers happen (much like I suggested by email for the student 'cumulative badge' scenario).

1 and 4 are both relatively easy and wouldn't need any UI changes. I have a slight preference for 1, because the outputs would look the same as the kind of output we'd get from the correct solution above, so we'd be able to transition to the proper way of doing things more easily. 

Maybe I should put this as a separate issue for discussion. :-)

**Comment by Callustian** [comment]
Badges are now signed per role, at the time they are issued. So if you want to verify the signature, you have to use one of the public keys I sent you. In general all you anchor (using the anchor service) is signed using a key related to the role that the token contains.

This means a student cannot sign a badge as a professor.

If there is more than a role in the token, the badge is signed using the first matching role in the sequence [student, recruiter, professor, administrator, default]

That is if a user has two roles the first matching role will sign the badge (i.e. [student, recruiter] shall sign as student)

If a role is not in the list, the default role is used

**Comment by Callustian** [comment]
@vkarakolis-epu If you think the solution satisfies your requirement, could you please close the issue? Thanks
